### PR TITLE
Sync with the fork

### PR DESCRIPTION
**Pull request by ixahedron**
For fun. Cleaned up some code too by doing an hlint pass.

### CODE REVIEW

**Comment by cognivore** [comment]
:heart: :yellow_heart: :blue_heart: :green_heart: 

Seems to work, but we also need to ensure that the migration shall happen well with the password store we have at doma engineering.

**Comment by cognivore** [comment]
So far, we merge this and test with the secrets I'll share with you in a bit.

**Comment by cognivore** [comment]
```
Fri Sep 13 13:33:27:109203053 sweater@rethink ~
λ veil allow sendgrid.com/apikey Ilona
Fri Sep 13 13:33:39:857893370 sweater@rethink ~
λ veil sync
Rebase finished!
Finished applying.
```

Feel free to test with the new build and please share something to `Bilbo` and `jonn@doma.dev`.

**Comment by ixahedron** [comment]
You're not going to believe it but I've found a bug in the upstream. The original passveil patches assumed we would be using RSA keys, and so verification consistently failed for my EDDSA key. Fixed it in a separate commit just in case!

And I've shared `veiltest` with you, let me know if it worked :octopus: Thanks for making me test!

**Comment by cognivore** [comment]
@ixahedron LOL sorry I didn't see this message.

Wait what the fuck! I am like 69% certain that someone was using ECDSA among our keys.

Great job!

**Pull request merged**
